language: node_js
node_js: '10'
sudo: required
branches:
  only:
    - develop
    - master
    - /^(?i:release|hotfix).*$/
services:
  - docker
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - SC_DEMO_USER_PASSWORD=schulcloud
    - FEATURE_TEAMS_ENABLED=true
    - IT_CLIENT_HOST=client
before_install:
  - mkdir -p integration-tests
  - mv !(integration-tests|node_modules) integration-tests
  # TODO remove next line
  - git clone -b aj/integration-tests https://github.com/schul-cloud/schulcloud-client.git schulcloud-client
  # TODO remove branch from next line
  - git clone -b aj/integration-tests https://github.com/schul-cloud/schulcloud-server.git schulcloud-server
  - git clone -b integration-test https://github.com/schul-cloud/docker-compose.git docker-compose
install:
  # TODO use "Images" Dockerfile to improve speed
  # - cd docker-compose && docker-compose -f docker-compose.integration-test-Images.yml up -d && cd ..
  - cd docker-compose && docker-compose -f docker-compose.integration-test-Build.yml up -d && cd ..
  - cd integration-tests && npm ci && cd ..
script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - cd integration-tests && npm run all && cd ..
after_script:
  - npm i -g @adrianjost/report-viewer
  - rv-upload -F **/integration-tests/reports/**/*.html
cache:
  directories:
    - schulcloud-client/node_modules