language: node_js
node_js: '10'
sudo: required
branches:
  only:
    - develop
    - master
    - /^(?i:release|hotfix).*$/
services:
  - docker
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - SC_DEMO_USER_PASSWORD=schulcloud
    - FEATURE_TEAMS_ENABLED=true
    - IT_CLIENT_HOST=client
before_install:
  - mkdir -p integration-tests
  - mv !(integration-tests) integration-tests
  - git clone https://github.com/schul-cloud/schulcloud-client.git schulcloud-client
  - git clone https://github.com/schul-cloud/schulcloud-server.git schulcloud-server
  - git clone https://github.com/schul-cloud/docker-compose.git docker-compose
install:
  - cd docker-compose && docker-compose -f docker-compose.integration-test.yml up -d && cd ..
  - cd schulcloud-client && npm ci && cd .. # client packages are needed for mocha
  - cd integration-tests && npm ci && cd ..
before_script:
  - cd schulcloud-server && npm run setup && cd ..
script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - cd integration-tests && npm run all && cd ..
cache:
  directories:
    - schulcloud-client/node_modules
    - integration-tests/node_modules