---
name: e2e unstable

on:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  tag-unstable:
    uses: hpi-schul-cloud/end-to-end-fork/.github/workflows/e2e.yml@main #ToDo remove branch ref
    with:
      branch_name: ${{ github.head_ref }}
      ref: ${{ github.ref }}
      e2e_tag: hello

